language: node_js
node_js:
  - "8"
cache:
  npm: true
  directories:
    - node_modules
# install:
#   - npm install

before_script:
  - npm install -g pug-cli

script:
  - npm run build
  # - mkdir dist
  # - ls dist
  # - npm run build-stylus
  # - ls dist
  # - npm run build-pug
  # - ls dist
  # - npm test
  

before_deploy:
  - npm install -g travis-ci-cloudfront-invalidation
  # - npm global add travis-ci-cloudfront-invalidation
  # - npm install -g travis-ci-cloudfront-invalidation pug stylus

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
  local-dir: dist
  on:
    branch: master

after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $CLOUDFRONT_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
